version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: [ "8000:8000" ]
    depends_on: [ db, redis ]
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: windborne
      POSTGRES_USER: windborne
      POSTGRES_PASSWORD: windborne
    ports: [ "5432:5432" ]
  redis:
    image: redis:7
    ports: [ "6379:6379" ]
  # Optional: Meilisearch for advanced search
  meili:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_MASTER_KEY: "changeme"
    ports: [ "7700:7700" ]
